# substitute: &substitute "bob"

labels:
  "test": *substitute

containers:
  memcached:
    image: memcached:latest
    extraSettings:
      imagePullPolicy: IfNotPresent
# alpine:
#   image: alpine:latest
#   extraSettings:
#     imagePullPolicy: IfNotPresent
#     command:
#       - /bin/sh
#       - -c
#       - |
#         echo "hello world 1" && sleep 3600

extraSettings:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
